'use client';
import { useState } from 'react';
import { workingSets, historySummary } from '@/lib/workout-performance';
import { convertWeight, RECORDS, timeText, type AthleteRecord } from '@/lib/training';
import type { PreviousExercise } from '@/lib/exercise-logging';
type History = PreviousExercise & { result_id: string };
function Trend({ points, unit }: { points: { value: number; date: string }[]; unit: string }) {
  if (points.length < 2) return <p className="text-sm text-zinc-200">At least two comparable saved performances are needed for a trend.</p>;
  const values = points.map(p => p.value), low = Math.min(...values), high = Math.max(...values), range = high - low || 1;
  const coords = points.map((p, i) => ({ ...p, x: 50 + i / (points.length - 1) * 280, y: 135 - (p.value - low) / range * 95 }));
  return <svg viewBox="0 0 360 190" className="w-full max-h-64" role="img" aria-label={`${unit} over time: ${points[0].value} to ${points[points.length - 1].value}`}><line x1="50" x2="330" y1="150" y2="150" stroke="#71717a"/><text x="8" y="40" fill="#e4e4e7" fontSize="14">{high.toFixed(1)}</text><text x="8" y="137" fill="#e4e4e7" fontSize="14">{low.toFixed(1)}</text><polyline points={coords.map(p => `${p.x},${p.y}`).join(' ')} fill="none" stroke="#e8bd55" strokeWidth="3"/>{coords.map((p, i) => <circle key={i} cx={p.x} cy={p.y} r="4" fill="#e8bd55"><title>{p.date}: {p.value.toFixed(1)} {unit}</title></circle>)}<text x="50" y="177" fill="#e4e4e7" fontSize="14">{points[0].date.slice(0, 10)}</text><text x="330" y="177" textAnchor="end" fill="#e4e4e7" fontSize="14">{points[points.length - 1].date.slice(0, 10)}</text></svg>;
}
export function PerformanceHistory({ history, records }: { history: History[]; records: AthleteRecord[] }) {
  const labels = [...new Set(history.map(h => h.label_key))].sort();
  const [label, setLabel] = useState(labels[0] || ''), [reps, setReps] = useState('all'), [unit, setUnit] = useState('lb'), [source, setSource] = useState('all'), [recordKey, setRecordKey] = useState('squat');
  const matching = history.filter(h => h.label_key === label && (source === 'all' || h.source === source));
  const repOptions = [...new Set(matching.flatMap(h => workingSets(h.entry).filter(s => s.completed && s.reps != null).map(s => s.reps!)))].sort((a, b) => a - b);
  const points = matching.flatMap(h => {
    const sets = workingSets(h.entry).filter(s => s.completed && s.weight != null && s.reps === Number(reps));
    return sets.length ? [{ date: h.completed_at, value: Math.max(...sets.map(s => convertWeight(s.weight!, h.entry.unit, unit))) }] : [];
  }).reverse().slice(-30);
  const recordPoints = records.filter(r => r.record_key === recordKey).map(r => ({ date: r.achieved_at, value: r.unit === 'seconds' ? Number(r.value) : convertWeight(Number(r.value), r.unit, unit) }));
  return <div className="space-y-8"><section className="ss-panel space-y-4"><h2 className="ss-label">Exercise history</h2><div className="grid gap-3 sm:grid-cols-2"><label>Exercise<select className="ss-field" value={label} onChange={e => { setLabel(e.target.value); setReps('all'); }}>{labels.map(l => <option key={l}>{l}</option>)}</select></label><label>Source<select className="ss-field" value={source} onChange={e => setSource(e.target.value)}><option value="all">All sources (individually labeled)</option><option>Program</option><option>Daily WOD</option></select></label><label>Compare reps<select className="ss-field" value={reps} onChange={e => setReps(e.target.value)}><option value="all">Choose a rep count for the trend</option>{repOptions.map(n => <option key={n} value={n}>{n} reps</option>)}</select></label><label>Trend unit<select className="ss-field" value={unit} onChange={e => setUnit(e.target.value)}><option>lb</option><option>kg</option></select></label></div>{reps !== 'all' && <><p className="text-sm text-amber-200">Heaviest completed working set at {reps} reps, in {unit}. Latest 30 matching performances; context still matters.</p><Trend points={points} unit={unit} /></>}<p className="text-sm text-zinc-300">Latest {history.length} saved exercise entries loaded, up to 1,000. Showing up to 50 sessions for this exercise.</p>{matching.slice(0, 50).map(h => <article key={`${h.result_id}-${h.label_key}`} className="border-t border-zinc-700 py-3"><p className="text-sm text-amber-200">{new Date(h.completed_at).toLocaleDateString()} · {h.source}</p><p className="text-zinc-100">{historySummary(h)}</p>{h.entry.notes && <p className="text-sm text-zinc-300">{h.entry.notes}</p>}</article>)}{!matching.length && <p>Save completed working sets to build your history.</p>}</section><section className="ss-panel space-y-4"><h2 className="ss-label">Lift and running record history</h2><label>Benchmark<select className="ss-field" value={recordKey} onChange={e => setRecordKey(e.target.value)}>{Object.entries(RECORDS).map(([key, record]) => <option key={key} value={key}>{record.label}</option>)}</select></label><Trend points={recordPoints} unit={RECORDS[recordKey as keyof typeof RECORDS].kind === 'time' ? 'seconds (lower is faster)' : unit} /><ul className="space-y-2">{records.filter(r => r.record_key === recordKey).slice(-20).reverse().map(r => <li key={r.id}>{r.achieved_at} · {r.unit === 'seconds' ? timeText(Number(r.value)) : `${r.value} ${r.unit}`}</li>)}</ul></section></div>;
}
