"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
type Account={user_id:string;email:string;display_name:string;role:string};
export function RoleManager({initialQuery=""}:{initialQuery?:string}){
 const router=useRouter();
 const [query,setQuery]=useState(initialQuery);const [matches,setMatches]=useState<Account[]>([]);const [selected,setSelected]=useState<Account|null>(null);const [role,setRole]=useState("member");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{let active=true;const seq=++generation.current;setMatches([]);if(query.trim().length<2)return;const timer=setTimeout(async()=>{const {data,error}=await createClient().rpc("search_role_accounts",{p_query:query});if(!active || seq!==generation.current)return;if(error)setMessage("Could not search accounts.");else setMatches(data||[]);},250);return()=>{clearTimeout(timer);active=false;};},[query]);
 return <div className="space-y-4"><label className="block">Search registered email<input autoComplete="off" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);setMessage("");}} className="mt-2 block w-full rounded border border-zinc-700 bg-zinc-900 p-3" placeholder="Type at least two characters" /></label><ul aria-label="Matching accounts">{matches.map(a=><li key={a.user_id}><button type="button" onClick={()=>{generation.current++;setSelected(a);setRole(a.role);setMatches([]);}} className="min-h-11 w-full border-b border-zinc-700 p-3 text-left">{a.email} - {a.display_name} ({a.role})</button></li>)}</ul>
 {selected && <form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(busy||!window.confirm(`Change ${selected.email} from ${selected.role} to ${role}?`))return;setBusy(true);try{const {error}=await createClient().rpc("assign_staff_role",{p_user:selected.user_id,p_role:role,p_expected:selected.role});if(error)throw error;setMessage(`Role saved for ${selected.email}.`);setSelected(null);setQuery("");router.refresh();}catch(e){setMessage(e && typeof e==='object' && 'message' in e?String(e.message):"Could not assign role.");}finally{setBusy(false);}}}><p>Selected: <strong>{selected.email}</strong> - {selected.display_name}. Current role: {selected.role}.</p><label>New role <select value={role} onChange={e=>setRole(e.target.value)} className="rounded bg-zinc-900 p-3">{["member","coach","owner"].map(r=><option key={r}>{r}</option>)}</select></label><button disabled={busy} className="min-h-11 rounded bg-orange-700 px-4 py-2">Confirm role change</button></form>}{message && <p role="status">{message}</p>}</div>;
}
