"use client";
import Image from "next/image";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";
export function StaffSecurity({destination}:{destination:string}){const [factor,setFactor]=useState('');const [qr,setQr]=useState('');const [secret,setSecret]=useState('');const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const router=useRouter();
 useEffect(()=>{let active=true;createClient().auth.mfa.listFactors().then(({data,error})=>{if(!active)return;if(error)setMessage(error.message);else setFactor(data?.totp.find(f=>f.status==='verified')?.id||'');});return()=>{active=false;};},[]);
 async function enroll(){setBusy(true);setMessage('');try{const db=createClient();const {data:factors,error:listError}=await db.auth.mfa.listFactors();if(listError)throw listError;const verified=factors?.totp[0];if(verified){setFactor(verified.id);return;}for(const old of factors?.all.filter(f=>f.factor_type==='totp' && f.status==='unverified')||[]){const {error}=await db.auth.mfa.unenroll({factorId:old.id});if(error)throw error;}const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'Sword and Shield staff'});if(error)throw error;setFactor(data.id);setQr(data.totp.qr_code);setSecret(data.totp.secret);}catch(e){setMessage(e instanceof Error?e.message:'Could not set up authenticator.');}finally{setBusy(false);}}
 return <div className="space-y-4">{!factor && <button disabled={busy} onClick={enroll} className="rounded bg-orange-700 p-3">Set up authenticator</button>}{qr && <><Image unoptimized src={qr.startsWith('data:')?qr:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(qr)}`} alt="Authenticator setup QR code" width={240} height={240} /><label className="block text-sm">Manual setup key<input id="staff-setup-key" readOnly value={secret} onFocus={e=>e.currentTarget.select()} className="mt-2 block w-full rounded border border-zinc-700 bg-zinc-900 p-3 font-mono" /></label><button type="button" onClick={async()=>{try{if(!navigator.clipboard)throw new Error('Manual copy required');await navigator.clipboard.writeText(secret);setMessage('Setup key copied. Paste it into your authenticator app.');}catch{const input=document.getElementById('staff-setup-key') as HTMLInputElement|null;input?.focus();input?.select();setMessage('Select and copy the setup key above.');}}} className="min-h-11 rounded border border-orange-700 px-4 py-2">Copy setup key</button><p>Using this phone? Copy the setup key, switch to your authenticator app, and add an account manually. Name it Sword and Shield and choose Time-based if asked. Return here and enter the six-digit code.</p><p>On a second device, you can scan the QR code instead.</p></>}{factor && <form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const {error}=await createClient().auth.mfa.challengeAndVerify({factorId:factor,code});if(error)throw error;setSecret('');setQr('');router.replace(destination);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'Verification failed.');}finally{setBusy(false);}}}><label>Authenticator code<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} className="ml-3 rounded bg-zinc-900 p-3" /></label><button disabled={busy} className="rounded bg-orange-700 p-3">Verify and continue</button></form>}{message && <p role="alert">{message}</p>}</div>;}
