import Link from "next/link";
import { notFound } from "next/navigation";
import { requireStaff } from "@/lib/staff-access";
import { StaffAction } from "@/components/StaffAction";
import type { PlanSession } from "@/types/database";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{week?:string}>}){
 const {db,role}=await requireStaff();const {id}=await params;const query=await searchParams;
 const {data:plan,error}=await db.from("training_plans").select("*").eq("id",id).maybeSingle();if(error)throw new Error("Could not load program.");if(!plan)notFound();
 const {data:days,error:dayError}=await db.from("plan_sessions").select("*").eq("plan_id",id).order("order_index").returns<PlanSession[]>();if(dayError)throw new Error("Could not load sessions.");
 const weeks=[...new Set((days||[]).map(d=>d.week_number))].sort((a,b)=>a-b);const week=weeks.includes(Number(query.week))?Number(query.week):weeks[0];const shown=(days||[]).filter(d=>d.week_number===week);
 const {data:suggestions,error:suggestionError}=shown.length?await db.from("plan_day_suggestions").select("*, profiles:author_id(display_name)").in("session_id",shown.map(s=>s.id)).order("created_at",{ascending:false}):{data:[],error:null};if(suggestionError)throw new Error("Could not load suggestions. Apply the staff migration.");
 return <div className="space-y-6"><Link href="/coach" className="text-orange-400">Back to review workspace</Link><h1 className="text-3xl font-bold">{plan.title}</h1><p className="whitespace-pre-wrap">{plan.description}</p><p>Intention: {plan.goal}</p><p>Fitness level: {plan.difficulty}. {plan.fitness_guidance}</p><p>Required equipment: {(plan.equipment_required||[]).join(', ')}</p><p>Suggested equipment: {(plan.equipment_suggested||[]).join(', ')}</p><Link href={`/coach/drafts?source=${id}`} className="inline-block rounded border border-orange-700 p-3">Propose a full program revision</Link><nav aria-label="Review weeks" className="flex flex-wrap gap-3">{weeks.map(w=><Link key={w} aria-current={week===w?'page':undefined} href={`?week=${w}`} className={`rounded border p-3 ${week===w?'border-orange-500':'border-zinc-700'}`}>Week {w}</Link>)}</nav>
 {shown.map(d=><section key={d.id} className="space-y-4 rounded border border-zinc-700 p-5"><h2 className="text-xl font-bold">Day {d.day_number}: {d.title}</h2><p>{d.session_type} / {d.estimated_minutes||'Unspecified'} minutes</p><p className="whitespace-pre-wrap">{d.description}</p><p className="whitespace-pre-wrap">{d.notes}</p><h3 className="font-bold">Exercises</h3>{d.exercises?.map(e=><div key={e.id} className="border-l border-orange-600 pl-3"><p>{e.label}: {e.sets} sets x {e.reps??'specified'} reps</p><p>{e.section} {e.superset?`/ Superset ${e.superset}`:''}</p><p className="whitespace-pre-wrap">{e.instructions}</p></div>)}<h3 className="font-bold">Loading and progression</h3>{d.prescriptions?.map(p=><div key={p.id}><p>{p.label}: {p.sets} x {p.reps}, {p.percent}% of {p.record_key} PR; {p.strategy==='previous'?'then previous-performance progression':'percentage prescription'}.</p><p className="text-sm text-zinc-400">Standard increase: {p.increment}{p.progression_mode==='percentage'?'%':` ${p.unit}`}. Comfortable increase: {p.comfortable_increment??p.increment*2}{p.progression_mode==='percentage'?'%':` ${p.unit}`}. Round to {p.rounding} {p.unit}. Missed sets/reps repeat the load. PR key: {p.record_key}.</p></div>)}<StaffAction rpc="add_day_suggestion" args={{p_session:d.id}} label="Add suggestion or revision" textKey="p_body" />{suggestions?.filter(s=>s.session_id===d.id).map(s=><article key={s.id} className="space-y-2 border-t border-zinc-700 pt-4"><p className="text-xs text-zinc-400">{s.profiles?.display_name || "Former staff member"} / {s.created_at} / {s.status}</p><p className="whitespace-pre-wrap">{s.body}</p>{s.owner_response && <p>Owner response: {s.owner_response}</p>}{role==='owner' && <div className="space-y-2"><StaffAction rpc="review_day_suggestion" args={{p_id:s.id,p_status:'accepted'}} textKey="p_response" label="Accept suggestion" /><StaffAction rpc="review_day_suggestion" args={{p_id:s.id,p_status:'declined',p_response:''}} label="Decline suggestion" /></div>}</article>)}</section>)}<p>Accepting a suggestion records your decision; it does not automatically change the live workout.</p></div>;
}
